name: mysql_auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.9
  flutter_secure_storage: ^5.0.2

flutter:
  uses-material-design: true
